# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johnson In A Shellnut
email: jw10231204@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello and welcome to my new site, currently, this site is just put-together with no direction
  as I try to decipher how everything works.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.PsyDSha.nard.ca/" # the base hostname & protocol for your site
twitter_username: *this is blank for now*
github_username:  Johnny1023

# Build settings
markdown: kramdown
